### ISSUE TITLE
ticking item can cause checkbox for next item to get ticked

### ISSUE THREAD

**Issue by rub1e** [msmichellegar/best-todo-ever#3]
say you have tasks A, B, C: ticking A causes A to be cleared but auto-ticks B (without clearing it). Then "unticking" B clears it and leaves C.

BUT

 this doesn't happen if you tick from the bottom, so ticking C just clears C

**Comment by NataliaLKB** [comment]
@rub1e. This is certainly a known bug, and we think it is to do with us attaching the event to a keyDown vs a keyUp event. When fixed, we will certainly let you know!

**Comment by msmichellegar** [comment]
We (inadvertently) fixed this by implementing pub/sub. Check it out now, and close the issue if you're satisfied @rub1e ;)

https://github.com/msmichellegar/best-todo-ever/commit/60968f61227e73c391e432406ca9b8529d648ce9

**Comment by rub1e** [comment]
app doesn't seem to be live on heroku right now so will have to check it out later and close issue then

**Comment by msmichellegar** [comment]
Just fixed that @rub1e. Check now.
